spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true7
    
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone:  http://eureka1:8761/eureka/
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream