spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
     
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultzone: http://eureka1:8761/eureka/
      fetch-registry: false
      
zuul:
  routes:
   item-service: /item-service/**
   user-service: /user-service/**
   order-service: /order-service/**
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream